### ISSUE TITLE
v0.12: all service actions fail with "'ServiceCall' object has no attribute 'target'"

### ISSUE THREAD

**Issue by wicksipedia** [calvinbui/home-assistant-solplanet#17]
### Describe the bug

After upgrading from v0.11 to v0.12, every Solplanet service action fails immediately with:

```
Error: 'ServiceCall' object has no attribute 'target'
```

This breaks all six services the integration exposes:

- `solplanet.set_schedule_slots`
- `solplanet.clear_schedule`
- `solplanet.set_meter_limit_power`
- `solplanet.set_meter_limit_current`
- `solplanet.set_meter_zero_power`
- `solplanet.disable_meter_power_limit`

### To reproduce

Any automation/script calling one of the services above. Minimal example:

```yaml
action: solplanet.clear_schedule
data:
  day: Sun
target:
  device_id: 64eddedf32b808b51e7ac24103bbd028
```

The trace shows the error is raised before any handler logic runs.

### Expected behaviour

Service executes (as it did on v0.11).

### Environment

- Solplanet integration: v0.12.0
- Home Assistant: 2026.4.3
- Installed via: HACS
