### PR TITLE
fix: stop reading nonexistent ServiceCall.target attribute

### LINKED ISSUE #17: v0.12: all service actions fail with "'ServiceCall' object has no attribute 'target'"
### Describe the bug

After upgrading from v0.11 to v0.12, every Solplanet service action fails immediately with:

```
Error: 'ServiceCall' object has no attribute 'target'
```

This breaks all six services the integration exposes:

- `solplanet.set_schedule_slots`
- `solplanet.clear_schedule`
- `solplanet.set_meter_limit_power`
- `solplanet.set_meter_limit_current`
- `solplanet.set_meter_zero_power`
- `solplanet.disable_meter_power_limit`

### To reproduce

Any automation/script calling one of the services above. Minimal example:

```yaml
action: solplanet.clear_schedule
data:
  day: Sun
target:
  device_id: 64eddedf32b808b51e7ac24103bbd028
```

The trace shows the error is raised before any handler logic runs.

### Expected behaviour

Service executes (as it did on v0.11).

### Environment

- Solplanet integration: v0.12.0
- Home Assistant: 2026.4.3
- Installed via: HACS

### PR DESCRIPTION
**Pull request by wicksipedia**
## Summary

- Fixes #17
- Removes a bogus `call.target` read in `_build_target()` (introduced in 1deeeb5). `homeassistant.core.ServiceCall` has no `target` attribute on any HA version — target data is merged into `call.data` by the service call machinery.
- Before the refactor, the inline blocks had `target = call.target if hasattr(call, 'target') else {}` — the `hasattr` was always False, so only the `call.data` merge ever ran. Dropping the guard broke all six services.
- All six service handlers (`set_schedule_slots`, `clear_schedule`, `set_meter_limit_power`, `set_meter_limit_current`, `set_meter_zero_power`, `disable_meter_power_limit`) currently fail on v0.12.0 with `'ServiceCall' object has no attribute 'target'`.

## Change

```diff
 def _build_target(call: ServiceCall) -> dict:
-    """Merge ServiceCall.target with legacy entity_id/device_id from call.data."""
-    target = dict(call.target)
+    """Extract entity_id/device_id from call.data.
+
+    Home Assistant merges any ``target:`` fields into ``call.data`` before the
+    handler runs; ``ServiceCall`` itself has no ``target`` attribute.
+    """
+    target: dict = {}
     if "entity_id" in call.data:
         target["entity_id"] = call.data["entity_id"]
     if "device_id" in call.data:
         target["device_id"] = call.data["device_id"]
     return target
```

## Test plan

- [ ] Call `solplanet.clear_schedule` with `target.device_id` → succeeds (was failing on v0.12.0)
- [x] Call `solplanet.clear_schedule` with legacy `data.device_id` (no `target:`) → still succeeds
- [ ] Smoke-test the other 5 services on a live inverter with battery + meter

### CODE REVIEW

**Comment by wicksipedia** [comment]
Sorry - PR raised prematurely

**Comment by wicksipedia** [comment]
Reopening as I've been able to test this successfully on my HA instance

**Comment by calvinbui** [comment]
released in [v0.12.1](https://github.com/calvinbui/home-assistant-solplanet/releases/tag/v0.12.1).

i don't use any services/selling of my battery back to the grid, so didn't come across this in my testing. i'll keep that in mind for next time.
